### ISSUE TITLE
实现从色彩渐变的边框

### ISSUE THREAD

**Issue by uyarn** [uyarn/uyarn#4]
### 起因
今天中午在群里看到有人在问如何实现这样一个样式 👇

![image](https://user-images.githubusercontent.com/26377630/120354802-5879ea80-c335-11eb-913b-d95171418c1d.png)
其实就是实现一个从中间向两边颜色渐变的边框，要求每条边都如此。
感觉还挺有意思，于是花了十分钟实现了一下。实现效果可以看👉 https://codesandbox.io/s/cold-sky-mbf62
先上代码

- DOM结构
```html
<div id="app">Hello World</div>
```
- 实现代码
```css
#app {
  width: 200px;
  height: 200px;
  color: #fff;
  line-height: 200px;
  text-align: center;
  border: 2px solid;
  border-image: linear-gradient(to right, black 0%, blue 50%, black 100%) 1 1 1
    1;
  position: relative;
}

#app::before,#app::after {
  content: "";
  position: absolute;
  top: 0;
  bottom: 0;
  width: 2px;
  background: linear-gradient(to bottom, black 0%, blue 50%, black 100%);
}

#app::before {
  left:0;
}

#app::after {
  right:0;
}

```
首先这里一定是需要用到渐变**line-gradient**函数。
接下来，马上想到的肯定是border-color。但是border-color是无法实现渐变的，不信可以试试。
#### 实现横向的渐变边框
所以这里又需要用到border-image这个属性来实现，它可以使用图片或者渐变函数。但是由于纵向和横向的渐变方向是不同的，纵向是从上到下由浅到深再浅，横向是从左到右由浅及深到浅，但由于我们无法给纵向和横向定义不同的border-image,比如**border-left-image**或者**border-bottom-image**。所以只用一个border-image来实现显然是无法做到的完整的效果的，但是不急，我们可以先实现纵向的，即代码中app的border-image属性：
`border-image: linear-gradient(to right, black 0%, blue 50%, black 100%) 1 1 1 1;`;
由于渐变方向是从左到右，且一开始的颜色为黑色，所以左右两边的边框都是看不见的黑色。

#### 实现纵向的渐变边框
接下来，我们需要实现纵向的渐变边框。如何实现呢，这时候就需要用到我们的before和after伪类来实现了。当我们的节点自身的盒子模型无法满足需求的时候，伪元素常常可以实现我们想要的效果。这里同样不例外。我们首先将节点自身的position设置为`relative`, before和after设置为`absolute`参照节点，接下来，让before做左边框（即left:0），赋予一个和border大小一样的width，接下来，将它的`background`设置为由上到下的渐变` background: linear-gradient(to bottom, black 0%, blue 50%, black 100%);` 即可。同理，after伪元素用来做右边框的原理也如此，区别只是它的位置变为了`right:0`。

至此，一个从中间向两边色彩渐变的边框即可实现 🚀
![image](https://user-images.githubusercontent.com/26377630/120358532-28344b00-c339-11eb-972d-bcb3f3ad9776.png)
